source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/options.vim
source $HOME/.config/nvim/themes/airline.vim
source $HOME/.config/nvim/keymappings.vim
lua require'plug-colorizer'
lua require'autopairs'
lua require'plug-gitsigns'
lua require'plug-comment'
lua require'lsp-config'
lua require'plug-telescope'
